 server.port: 9091
 server.ssl.key-store: classpath:keystore.p12
 server.ssl.key-store-password: 123456
 server.ssl.keyStoreType: PKCS12
 server.ssl.keyAlias: tomcat 


 ### sqlite需要自己配置连接方式
 jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
 logging:
  level:
    ROOT: INFO